- name: Install ufw - firewall
  apt:
    name: ufw
    state: present
    update_cache: true
    
- name: set logging
  ufw: 
    logging=on
    state=reset

- name: allow port 22 - for list of ipaddresses defined in group_vars
  ufw: 
    rule=allow
    port=22
    src="{{ item}}"
  loop: "{{ ssh_ipaddresses }}"

- name: allow port 80
  ufw: 
    rule=allow 
    port=80
  when: inventory_hostname in groups.webservers
    

- name: enable ufw
  ufw: state=enabled policy=deny


- lineinfile:
    dest: /etc/default/ufw
    regexp: '^IPV6'
    line: 'IPV6=no'
    state: present
  notify: restart_ufw
